### ISSUE TITLE
about the qmof.json

### ISSUE THREAD

**Issue by xiaowangfeng** [Andrew-S-Rosen/QMOF#38]
I have find the error that the  qmof.json doesn't have the 'structure'. And so  the code will have problem.

import os
import json
from pymatgen.core import Structure

# ------Settings------#
struct_json_path = "E:\GANN-main\qmof_database\qmof_structure_data.json"  # path to structure json
cif_folder_path = "E:\GANN-main\qmof_database\qmof_cif"  # path to folder where CIFs will be stored
write_site_props = True  # if site properties should be written to CIF
only_ddec_charge = False  # set to True if you only want _atom_site_charge flags
# ------Settings------#

# Make new folder to store CIFs
if not os.path.exists(cif_folder_path):
    os.mkdir(cif_folder_path)

# Read in structure data
with open("E:\GANN-main\qmof_database\qmof.json") as f:
    qmof_struct_data = json.load(f)

# Loop over structures and write each one out to a CIF
qmof_structs = {}
for entry in qmof_struct_data:

    qmof_id = entry["qmof_id"]  # name for CIF
    print(f"Writing {qmof_id}")

    struct = Structure.from_dict(entry["structure"])  # Pymatgen structure
    cif_path = os.path.join(cif_folder_path, f"{qmof_id}.cif")  # path to write CIF
    struct.to(filename=cif_path)  # write CIF
    properties = dict(sorted(struct.site_properties.items()))  # fetch site properties

    # Overwrite CIF with site properties
    if write_site_props:
        new_cif = ""
        i = 0
        prop_lines = False

        with open(cif_path, "r") as f:
            for line in f:
                if "_atom_site_occupancy" in line:
                    new_cif += line
                    if only_ddec_charge:
                        new_cif += f" _atom_site_charge\n"
                    else:
                        for key in properties.keys():
                            new_cif += f" _atom_site_{key}\n"
                    prop_lines = True
                    continue

                if i == len(struct):
                    prop_lines = False

                if prop_lines:
                    new_cif += line.strip()
                    if only_ddec_charge:
                        new_cif += f"  {properties['pbe_ddec_charge'][i]}"
                    else:
                        for value_sets in properties.values():
                            new_cif += f"  {value_sets[i]}"
                    new_cif += "\n"
                    i += 1
                else:
                    new_cif += line

        # Write out new CIF
        with open(cif_path, "w") as f:
            f.write(new_cif)

Traceback (most recent call last):
  File "E:\GANN-main\qmof_database\scripts\make_cifs.py", line 27, in <module>
    struct = Structure.from_dict(entry["structure"])  # Pymatgen structure
KeyError: 'structure'

can you tell me how to solve it?  
thank you for your reply

**Comment by Andrew-S-Rosen** [comment]
Please stop spamming me about this. This is now the 4th or 5th time you have messaged me about this. 

Follow the instructions and use the structure-containing JSON file. Regardless, all the data is there available to you. I cannot provide 1:1 technical support for you to debug your particular issues.

**Comment by xiaowangfeng** [comment]
I'm sorry to bother you, professor. I will try my best to solve this problem. Thank you for your advice and suggestions

**Comment by Andrew-S-Rosen** [comment]
Thank you.

You wrote

```python
with open("E:\GANN-main\qmof_database\qmof.json") as f:
   qmof_struct_data = json.load(f)
```

That is not the `qmof_structure_data.json`.

**Comment by xiaowangfeng** [comment]
thank you very much， I have solve the problem&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Andrew-S-Rosen/QMOF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月28日(星期二) 中午11:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Andrew-S-Rosen/QMOF] about the qmof.json (Issue #38)





 
Thank you.
 
You wrote
 with open("E:\GANN-main\qmof_database\qmof.json") as f:    qmof_struct_data = json.load(f)
 
That is not the qmof_structure_data.json.
