### ISSUE TITLE
about the atom_fea

### ISSUE THREAD

**Issue by xiaowangfeng** [Andrew-S-Rosen/QMOF#39]
Dear authors,

I read your comment and I noticed that CGCNN uses 9 atomic descriptors in table S2. After one hot  encoding the feature vector dimension should be 93 but why is it 72 after I have run it.I would like to know how did you solve this problem.

**Comment by Andrew-S-Rosen** [comment]
Thank you for your question. Table S2 does not seem to refer to anything related to CGCNN, so I'm not 100% sure which table you are referring to. That said, if I recall correctly, the precise feature vector dimension does not substantially change the results so it is probably fine regardless.

**Comment by Andrew-S-Rosen** [comment]
It has been a while, but your question may also be related to the following text in the SI:
![image](https://github.com/user-attachments/assets/4f70eaab-e14a-433a-b22b-e9c9a98d5521)

**Comment by xiaowangfeng** [comment]
Thanks for the reply, my reason is that I was looking at the CGCNN paper earlier and noticed that you have made some improvements to atom_init. I am currently trying to build on your work. My current problem is how to differentiate between the atomic features I extracted (72 dimensions, not 93 as in the CGCNN paper. I don't know the reason for this) among the 9 atomic descriptors. Another question is what to do if I want to evaluate the relative importance of the 9 different descriptors.
Looking forward to your reply.

**Comment by Andrew-S-Rosen** [comment]
Thanks for your question. Unfortunately, I am unsured about the difference in dimensions (72 vs. 93). Perhaps I knew at one point, but it's not immediately clear to me now. I'll let you know if something comes to mind. Ultimately, I don't think the changes to `atom_init` actually had any statistical impact on the resulting model performance if that makes you feel a bit better about things. 

As for evaluating the relative importance, that's a different question entirely that is very much subject to interpretation. You could always remove one and see how it impacts the results.

**Comment by xiaowangfeng** [comment]
Thanks, I would also like to ask a question on how to extract the different atom descriptors from the atom features generated by atom_init.

**Comment by Andrew-S-Rosen** [comment]
That is beyond the scope of this issue report and repo. The question you are asking is related to CGCNN specifically. I did not code up CGCNN and so that is not a question for me.
